/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  PayableOverrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface DisperseInterface extends ethers.utils.Interface {
  functions: {
    "disperseEther(address[],uint256[])": FunctionFragment;
    "disperseTokenERC1155(address[],address[],uint256[],uint256[],bytes[])": FunctionFragment;
    "disperseTokenERC20(address,address[],uint256[])": FunctionFragment;
    "disperseTokenERC721(address[],address[],uint256[])": FunctionFragment;
  };

  encodeFunctionData(
    functionFragment: "disperseEther",
    values: [string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disperseTokenERC1155",
    values: [string[], string[], BigNumberish[], BigNumberish[], BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disperseTokenERC20",
    values: [string, string[], BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "disperseTokenERC721",
    values: [string[], string[], BigNumberish[]]
  ): string;

  decodeFunctionResult(
    functionFragment: "disperseEther",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disperseTokenERC1155",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disperseTokenERC20",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "disperseTokenERC721",
    data: BytesLike
  ): Result;

  events: {};
}

export class Disperse extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: DisperseInterface;

  functions: {
    disperseEther(
      recipients: string[],
      values: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    "disperseEther(address[],uint256[])"(
      recipients: string[],
      values: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<ContractTransaction>;

    disperseTokenERC1155(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "disperseTokenERC1155(address[],address[],uint256[],uint256[],bytes[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    disperseTokenERC20(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "disperseTokenERC20(address,address[],uint256[])"(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    disperseTokenERC721(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "disperseTokenERC721(address[],address[],uint256[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  disperseEther(
    recipients: string[],
    values: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  "disperseEther(address[],uint256[])"(
    recipients: string[],
    values: BigNumberish[],
    overrides?: PayableOverrides
  ): Promise<ContractTransaction>;

  disperseTokenERC1155(
    tokens: string[],
    recipients: string[],
    tokenIds: BigNumberish[],
    amounts: BigNumberish[],
    datas: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "disperseTokenERC1155(address[],address[],uint256[],uint256[],bytes[])"(
    tokens: string[],
    recipients: string[],
    tokenIds: BigNumberish[],
    amounts: BigNumberish[],
    datas: BytesLike[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  disperseTokenERC20(
    token: string,
    recipients: string[],
    values: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "disperseTokenERC20(address,address[],uint256[])"(
    token: string,
    recipients: string[],
    values: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  disperseTokenERC721(
    tokens: string[],
    recipients: string[],
    tokenIds: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "disperseTokenERC721(address[],address[],uint256[])"(
    tokens: string[],
    recipients: string[],
    tokenIds: BigNumberish[],
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    disperseEther(
      recipients: string[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "disperseEther(address[],uint256[])"(
      recipients: string[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    disperseTokenERC1155(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    "disperseTokenERC1155(address[],address[],uint256[],uint256[],bytes[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: CallOverrides
    ): Promise<void>;

    disperseTokenERC20(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "disperseTokenERC20(address,address[],uint256[])"(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    disperseTokenERC721(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;

    "disperseTokenERC721(address[],address[],uint256[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {};

  estimateGas: {
    disperseEther(
      recipients: string[],
      values: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    "disperseEther(address[],uint256[])"(
      recipients: string[],
      values: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<BigNumber>;

    disperseTokenERC1155(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "disperseTokenERC1155(address[],address[],uint256[],uint256[],bytes[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    disperseTokenERC20(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "disperseTokenERC20(address,address[],uint256[])"(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    disperseTokenERC721(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;

    "disperseTokenERC721(address[],address[],uint256[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    disperseEther(
      recipients: string[],
      values: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    "disperseEther(address[],uint256[])"(
      recipients: string[],
      values: BigNumberish[],
      overrides?: PayableOverrides
    ): Promise<PopulatedTransaction>;

    disperseTokenERC1155(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "disperseTokenERC1155(address[],address[],uint256[],uint256[],bytes[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      amounts: BigNumberish[],
      datas: BytesLike[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    disperseTokenERC20(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "disperseTokenERC20(address,address[],uint256[])"(
      token: string,
      recipients: string[],
      values: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    disperseTokenERC721(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "disperseTokenERC721(address[],address[],uint256[])"(
      tokens: string[],
      recipients: string[],
      tokenIds: BigNumberish[],
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
