/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */

import {
  ethers,
  EventFilter,
  Signer,
  BigNumber,
  BigNumberish,
  PopulatedTransaction,
} from "ethers";
import {
  Contract,
  ContractTransaction,
  Overrides,
  CallOverrides,
} from "@ethersproject/contracts";
import { BytesLike } from "@ethersproject/bytes";
import { Listener, Provider } from "@ethersproject/providers";
import { FunctionFragment, EventFragment, Result } from "@ethersproject/abi";

interface ViewsInterface extends ethers.utils.Interface {
  functions: {
    "owner()": FunctionFragment;
    "paused()": FunctionFragment;
    "renounceOwnership()": FunctionFragment;
    "seeBuyOrderFor(address,address)": FunctionFragment;
    "seeBuyOrderForIds(address,uint256[])": FunctionFragment;
    "seeBuyOrders(address)": FunctionFragment;
    "seeManagers(address)": FunctionFragment;
    "seeManagersFor(address,address)": FunctionFragment;
    "seeManagersForIds(address,uint256[])": FunctionFragment;
    "seeSellOrderFor(address,address)": FunctionFragment;
    "seeSellOrderForIds(address,uint256[])": FunctionFragment;
    "seeSellOrders(address)": FunctionFragment;
    "seeTrades(address)": FunctionFragment;
    "seeTradesFor(address,address)": FunctionFragment;
    "seeTradesForIds(address,uint256[])": FunctionFragment;
    "transferOwnership(address)": FunctionFragment;
  };

  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(functionFragment: "paused", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "seeBuyOrderFor",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "seeBuyOrderForIds",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "seeBuyOrders",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "seeManagers", values: [string]): string;
  encodeFunctionData(
    functionFragment: "seeManagersFor",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "seeManagersForIds",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "seeSellOrderFor",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "seeSellOrderForIds",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "seeSellOrders",
    values: [string]
  ): string;
  encodeFunctionData(functionFragment: "seeTrades", values: [string]): string;
  encodeFunctionData(
    functionFragment: "seeTradesFor",
    values: [string, string]
  ): string;
  encodeFunctionData(
    functionFragment: "seeTradesForIds",
    values: [string, BigNumberish[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [string]
  ): string;

  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(functionFragment: "paused", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeBuyOrderFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeBuyOrderForIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeBuyOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeManagers",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeManagersFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeManagersForIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeSellOrderFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeSellOrderForIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeSellOrders",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "seeTrades", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "seeTradesFor",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "seeTradesForIds",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;

  events: {
    "OwnershipTransferred(address,address)": EventFragment;
    "Paused(address)": EventFragment;
    "Unpaused(address)": EventFragment;
  };

  getEvent(nameOrSignatureOrTopic: "OwnershipTransferred"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Paused"): EventFragment;
  getEvent(nameOrSignatureOrTopic: "Unpaused"): EventFragment;
}

export class Views extends Contract {
  connect(signerOrProvider: Signer | Provider | string): this;
  attach(addressOrName: string): this;
  deployed(): Promise<this>;

  on(event: EventFilter | string, listener: Listener): this;
  once(event: EventFilter | string, listener: Listener): this;
  addListener(eventName: EventFilter | string, listener: Listener): this;
  removeAllListeners(eventName: EventFilter | string): this;
  removeListener(eventName: any, listener: Listener): this;

  interface: ViewsInterface;

  functions: {
    owner(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    "owner()"(overrides?: CallOverrides): Promise<{
      0: string;
    }>;

    paused(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    "paused()"(overrides?: CallOverrides): Promise<{
      0: boolean;
    }>;

    renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

    seeBuyOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    "seeBuyOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    seeBuyOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    "seeBuyOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    seeBuyOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    "seeBuyOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    seeManagers(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[];
    }>;

    "seeManagers(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[];
    }>;

    seeManagersFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[];
    }>;

    "seeManagersFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[];
    }>;

    seeManagersForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[];
    }>;

    "seeManagersForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[];
    }>;

    seeSellOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    "seeSellOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    seeSellOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    "seeSellOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    seeSellOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    "seeSellOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[];
    }>;

    seeTrades(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[];
    }>;

    "seeTrades(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[];
    }>;

    seeTradesFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[];
    }>;

    "seeTradesFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[];
    }>;

    seeTradesForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[];
    }>;

    "seeTradesForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<{
      0: {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[];
    }>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<ContractTransaction>;
  };

  owner(overrides?: CallOverrides): Promise<string>;

  "owner()"(overrides?: CallOverrides): Promise<string>;

  paused(overrides?: CallOverrides): Promise<boolean>;

  "paused()"(overrides?: CallOverrides): Promise<boolean>;

  renounceOwnership(overrides?: Overrides): Promise<ContractTransaction>;

  "renounceOwnership()"(overrides?: Overrides): Promise<ContractTransaction>;

  seeBuyOrderFor(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  "seeBuyOrderFor(address,address)"(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  seeBuyOrderForIds(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  "seeBuyOrderForIds(address,uint256[])"(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  seeBuyOrders(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  "seeBuyOrders(address)"(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  seeManagers(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      _id: BigNumber;
      _address: string;
      _owner: string;
      _supply: BigNumber;
      _nftaddr: string;
      _nftid: BigNumber;
      _quantity: BigNumber;
      _erc721: boolean;
      _meta: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: boolean;
      8: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
    }[]
  >;

  "seeManagers(address)"(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      _id: BigNumber;
      _address: string;
      _owner: string;
      _supply: BigNumber;
      _nftaddr: string;
      _nftid: BigNumber;
      _quantity: BigNumber;
      _erc721: boolean;
      _meta: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: boolean;
      8: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
    }[]
  >;

  seeManagersFor(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      _id: BigNumber;
      _address: string;
      _owner: string;
      _supply: BigNumber;
      _nftaddr: string;
      _nftid: BigNumber;
      _quantity: BigNumber;
      _erc721: boolean;
      _meta: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: boolean;
      8: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
    }[]
  >;

  "seeManagersFor(address,address)"(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      _id: BigNumber;
      _address: string;
      _owner: string;
      _supply: BigNumber;
      _nftaddr: string;
      _nftid: BigNumber;
      _quantity: BigNumber;
      _erc721: boolean;
      _meta: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: boolean;
      8: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
    }[]
  >;

  seeManagersForIds(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      _id: BigNumber;
      _address: string;
      _owner: string;
      _supply: BigNumber;
      _nftaddr: string;
      _nftid: BigNumber;
      _quantity: BigNumber;
      _erc721: boolean;
      _meta: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: boolean;
      8: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
    }[]
  >;

  "seeManagersForIds(address,uint256[])"(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      _id: BigNumber;
      _address: string;
      _owner: string;
      _supply: BigNumber;
      _nftaddr: string;
      _nftid: BigNumber;
      _quantity: BigNumber;
      _erc721: boolean;
      _meta: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
      0: BigNumber;
      1: string;
      2: string;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: BigNumber;
      7: boolean;
      8: {
        name: string;
        description: string;
        image: string;
        json: string;
        0: string;
        1: string;
        2: string;
        3: string;
      };
    }[]
  >;

  seeSellOrderFor(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  "seeSellOrderFor(address,address)"(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  seeSellOrderForIds(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  "seeSellOrderForIds(address,uint256[])"(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  seeSellOrders(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  "seeSellOrders(address)"(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      amount: BigNumber;
      amountExecuted: BigNumber;
      cost: BigNumber;
      costExecuted: BigNumber;
      currency: string;
      fillOrKill: boolean;
      at: BigNumber;
      owner: string;
      buy: boolean;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: BigNumber;
      5: string;
      6: boolean;
      7: BigNumber;
      8: string;
      9: boolean;
    }[]
  >;

  seeTrades(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      orderId: BigNumber;
      amount: BigNumber;
      cost: BigNumber;
      currency: string;
      at: BigNumber;
      buyer: string;
      seller: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: string;
      7: string;
    }[]
  >;

  "seeTrades(address)"(
    _contract: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      orderId: BigNumber;
      amount: BigNumber;
      cost: BigNumber;
      currency: string;
      at: BigNumber;
      buyer: string;
      seller: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: string;
      7: string;
    }[]
  >;

  seeTradesFor(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      orderId: BigNumber;
      amount: BigNumber;
      cost: BigNumber;
      currency: string;
      at: BigNumber;
      buyer: string;
      seller: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: string;
      7: string;
    }[]
  >;

  "seeTradesFor(address,address)"(
    _contract: string,
    owner: string,
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      orderId: BigNumber;
      amount: BigNumber;
      cost: BigNumber;
      currency: string;
      at: BigNumber;
      buyer: string;
      seller: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: string;
      7: string;
    }[]
  >;

  seeTradesForIds(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      orderId: BigNumber;
      amount: BigNumber;
      cost: BigNumber;
      currency: string;
      at: BigNumber;
      buyer: string;
      seller: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: string;
      7: string;
    }[]
  >;

  "seeTradesForIds(address,uint256[])"(
    _contract: string,
    ids: BigNumberish[],
    overrides?: CallOverrides
  ): Promise<
    {
      id: BigNumber;
      orderId: BigNumber;
      amount: BigNumber;
      cost: BigNumber;
      currency: string;
      at: BigNumber;
      buyer: string;
      seller: string;
      0: BigNumber;
      1: BigNumber;
      2: BigNumber;
      3: BigNumber;
      4: string;
      5: BigNumber;
      6: string;
      7: string;
    }[]
  >;

  transferOwnership(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  "transferOwnership(address)"(
    newOwner: string,
    overrides?: Overrides
  ): Promise<ContractTransaction>;

  callStatic: {
    owner(overrides?: CallOverrides): Promise<string>;

    "owner()"(overrides?: CallOverrides): Promise<string>;

    paused(overrides?: CallOverrides): Promise<boolean>;

    "paused()"(overrides?: CallOverrides): Promise<boolean>;

    renounceOwnership(overrides?: CallOverrides): Promise<void>;

    "renounceOwnership()"(overrides?: CallOverrides): Promise<void>;

    seeBuyOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    "seeBuyOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    seeBuyOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    "seeBuyOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    seeBuyOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    "seeBuyOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    seeManagers(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[]
    >;

    "seeManagers(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[]
    >;

    seeManagersFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[]
    >;

    "seeManagersFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[]
    >;

    seeManagersForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[]
    >;

    "seeManagersForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        _id: BigNumber;
        _address: string;
        _owner: string;
        _supply: BigNumber;
        _nftaddr: string;
        _nftid: BigNumber;
        _quantity: BigNumber;
        _erc721: boolean;
        _meta: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
        0: BigNumber;
        1: string;
        2: string;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: BigNumber;
        7: boolean;
        8: {
          name: string;
          description: string;
          image: string;
          json: string;
          0: string;
          1: string;
          2: string;
          3: string;
        };
      }[]
    >;

    seeSellOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    "seeSellOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    seeSellOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    "seeSellOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    seeSellOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    "seeSellOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        amount: BigNumber;
        amountExecuted: BigNumber;
        cost: BigNumber;
        costExecuted: BigNumber;
        currency: string;
        fillOrKill: boolean;
        at: BigNumber;
        owner: string;
        buy: boolean;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: BigNumber;
        5: string;
        6: boolean;
        7: BigNumber;
        8: string;
        9: boolean;
      }[]
    >;

    seeTrades(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[]
    >;

    "seeTrades(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[]
    >;

    seeTradesFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[]
    >;

    "seeTradesFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[]
    >;

    seeTradesForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[]
    >;

    "seeTradesForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<
      {
        id: BigNumber;
        orderId: BigNumber;
        amount: BigNumber;
        cost: BigNumber;
        currency: string;
        at: BigNumber;
        buyer: string;
        seller: string;
        0: BigNumber;
        1: BigNumber;
        2: BigNumber;
        3: BigNumber;
        4: string;
        5: BigNumber;
        6: string;
        7: string;
      }[]
    >;

    transferOwnership(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: CallOverrides
    ): Promise<void>;
  };

  filters: {
    OwnershipTransferred(
      previousOwner: string | null,
      newOwner: string | null
    ): EventFilter;

    Paused(account: null): EventFilter;

    Unpaused(account: null): EventFilter;
  };

  estimateGas: {
    owner(overrides?: CallOverrides): Promise<BigNumber>;

    "owner()"(overrides?: CallOverrides): Promise<BigNumber>;

    paused(overrides?: CallOverrides): Promise<BigNumber>;

    "paused()"(overrides?: CallOverrides): Promise<BigNumber>;

    renounceOwnership(overrides?: Overrides): Promise<BigNumber>;

    "renounceOwnership()"(overrides?: Overrides): Promise<BigNumber>;

    seeBuyOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeBuyOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeBuyOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeBuyOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeBuyOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeBuyOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeManagers(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeManagers(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeManagersFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeManagersFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeManagersForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeManagersForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeSellOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeSellOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeSellOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeSellOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeSellOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeSellOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeTrades(_contract: string, overrides?: CallOverrides): Promise<BigNumber>;

    "seeTrades(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeTradesFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeTradesFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    seeTradesForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    "seeTradesForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<BigNumber>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<BigNumber>;
  };

  populateTransaction: {
    owner(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "owner()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    paused(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    "paused()"(overrides?: CallOverrides): Promise<PopulatedTransaction>;

    renounceOwnership(overrides?: Overrides): Promise<PopulatedTransaction>;

    "renounceOwnership()"(overrides?: Overrides): Promise<PopulatedTransaction>;

    seeBuyOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeBuyOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeBuyOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeBuyOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeBuyOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeBuyOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeManagers(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeManagers(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeManagersFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeManagersFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeManagersForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeManagersForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeSellOrderFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeSellOrderFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeSellOrderForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeSellOrderForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeSellOrders(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeSellOrders(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeTrades(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeTrades(address)"(
      _contract: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeTradesFor(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeTradesFor(address,address)"(
      _contract: string,
      owner: string,
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    seeTradesForIds(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    "seeTradesForIds(address,uint256[])"(
      _contract: string,
      ids: BigNumberish[],
      overrides?: CallOverrides
    ): Promise<PopulatedTransaction>;

    transferOwnership(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;

    "transferOwnership(address)"(
      newOwner: string,
      overrides?: Overrides
    ): Promise<PopulatedTransaction>;
  };
}
